const formSections = [
    // {
    //     title: "Offering Type",
    //     fields: [
    //         {
    //             name: "propertyType",
    //             label: "Property Type",
    //             type: "select",
    //             placeholder: "Select Property Type",
    //             options: [
    //                 { value: "residential", label: "Residential" },
    //                 { value: "commercial", label: "Commercial" },
    //             ],
    //             required: true,
    //         },
    //         {
    //             name: "listingType",
    //             label: "Listing Type",
    //             type: "select",
    //             placeholder: "Select Listing Type",
    //             options: [
    //                 { value: "rental", label: "Rental" },
    //                 { value: "sale", label: "Sale" },
    //             ],
    //             required: true,
    //         },
    //     ],
    // },
    {
        title: "Title and Description",
        className: "space-y-4",
        fields: [
            {
                name: "title_english",
                label: "Property Title (English)",
                type: "text",
                placeholder: "Enter Property Title (English)",
                required: true,
            },
            {
                name: "description_english",
                label: "Description (English)",
                type: "textarea",
                placeholder: "Enter Description (English)",
                required: true,
            },
            {
                name: "title_arabic",
                label: "Property Title (Arabic)",
                type: "text",
                placeholder: "Enter Property Title (Arabic)",
                required: false,
            },
            {
                name: "description_arabic",
                label: "Description (Arabic)",
                type: "textarea",
                placeholder: "Enter Description (Arabic)",
                required: false,
            },
        ],
    },
    {
        title: "Management",
        className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4",
        fields: [
            {
                name: "referenceNumber",
                label: "Reference Number",
                type: "text",
                placeholder: "Enter Reference Number",
                required: true,
            },
            {
                name: "listingAgent",
                label: "Listing agent",
                type: "select",
                placeholder: "Select Listing Agent",
                options: [
                    { value: "area1", label: "Area 1" },
                    { value: "area2", label: "Area 2" },
                    { value: "area3", label: "Area 3" },
                ],
                required: true,
            },
            {
                name: "listingOwner",
                label: "Listing Owner",
                type: "select",
                placeholder: "Select Listing Owner",
                options: [
                    { value: "area1", label: "Area 1" },
                    { value: "area2", label: "Area 2" },
                    { value: "area3", label: "Area 3" },
                ],
                required: true,
            },
            {
                name: "landlordName",
                label: "Landlord Name",
                type: "text",
                placeholder: "Enter Landlord Name",
                required: true,
            },
            {
                name: "landlordEmail",
                label: "Landlord Email",
                type: "email",
                placeholder: "Enter Landlord Email",
                required: true,
            },
            {
                name: "landlordPhone",
                label: "Landlord Phone",
                type: "tel",
                placeholder: "Enter Landlord Phone",
                required: true,
            },
            {
                name: "availability",
                label: "Availability",
                type: "select",
                placeholder: "Select Availability",
                options: [
                    { value: "available", label: "Available" },
                    { value: "underOffer", label: "Under Offer" },
                    { value: "reserved", label: "Reserved" },
                    { value: "sold", label: "Sold" },
                ],
                required: false,
            },
            {
                name: "availableDateFrom",
                label: "Available Date From",
                type: "date",
                placeholder: "Enter Available Date From",
                required: false,
            },
            {
                name: "availableDateTo",
                label: "Available Date To",
                type: "date",
                placeholder: "Enter Available Date To",
                required: false,
            },
        ],
    },
    {
        title: "Property Specifications",
        className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4",
        fields: [
            {
                name: "titleDeed",
                label: "Title Deed",
                type: "text",
                placeholder: "Enter Title Deed",
            },
            {
                name: "PropertyType",
                label: "Property Type",
                type: "select",
                placeholder: "Select Property Type",
                options: [
                    { value: "villa", label: "Villa" },
                    { value: "apertment", label: "Apertment" },
                ],
                required: true,
            },
            {
                name: "size",
                label: "Size (Sq.ft)",
                type: "number",
                placeholder: "Enter Size (Sq.ft)",
                required: true,
            },
            {
                name: "unitNo",
                label: "Unit No.",
                type: "number",
                placeholder: "Enter Unit No.",
                required: true,
            },
            {
                name: "bedrooms",
                label: "No. of Bedrooms",
                type: "select",
                placeholder: "Select No. of Bedrooms",
                options: [
                    { value: "1", label: "1" },
                    { value: "2", label: "2" },
                    { value: "3", label: "3" },
                    { value: "4", label: "4" },
                ],
                required: true,
            },
            {
                name: "bathrooms",
                label: "No. of Bathrooms",
                type: "number",
                placeholder: "Enter No. of Bathrooms",
                required: true,
            },
            {
                name: "parkingSpaces",
                label: "No. of Parking Spaces",
                type: "number",
                placeholder: "Enter No. of Parking Spaces",
            },
            {
                name: "furnished",
                label: "Furnished?",
                type: "select",
                placeholder: "Select Furnished",
                options: [
                    { value: "yes", label: "Yes" },
                    { value: "no", label: "No" },
                ],
                required: false,
            },
            {
                name: "totalPlotSize",
                label: "Total Plot Size (Sq.ft)",
                type: "number",
                placeholder: "Enter Total Plot Size (Sq.ft)",
            },
            {
                name: "lotSize",
                label: "Lot Size (Sq.ft)",
                type: "number",
                placeholder: "Enter Lot Size (Sq.ft)",
            },
            {
                name: "buildUpArea",
                label: "Build-up Area",
                type: "number",
                placeholder: "Enter Build-up Area",
            },
            {
                name: "layoutType",
                label: "Layout Type",
                type: "select",
                placeholder: "Select Layout Type",
                options: [
                    { value: "apartment", label: "Apartment" },
                    { value: "townhouse", label: "Townhouse" },
                    { value: "villa", label: "Villa" },
                ],
            },
            {
                name: "projectName",
                label: "Project Name",
                type: "text",
                placeholder: "Enter Project Name",
            },
            {
                name: "projectStatus",
                label: "Project Status",
                type: "select",
                placeholder: "Select Project Status",
                options: [
                    { value: "Ready Secondary", label: "Ready Secondary" },
                    {
                        value: "Off-plan Secondary",
                        label: "Off-plan Secondary",
                    },
                    { value: "Ready Promary", label: "Ready Promary" },
                    { value: "Off-plan Primary", label: "Off-plan Primary" },
                ],
                required: false,
            },
            {
                name: "saleType",
                label: "Sale Type (if off-plan)",
                type: "select",
                placeholder: "Select Sale Type (if off-plan)",
                options: [
                    { value: "freehold", label: "Free Hold" },
                    { value: "new", label: "New" },
                    { value: "resale", label: "Resale" },
                ],
                required: false,
            },
            {
                name: "developer",
                label: "Developer",
                type: "select",
                placeholder: "Select Developer",
                options: [
                    {
                        value: "elegance-holding",
                        label: "Elegance Holding",
                    },
                    { value: "other", label: "Other" },
                ],
                required: false,
            },
            {
                name: "buildYear",
                label: "Build Year",
                type: "number",
                placeholder: "Enter Build Year",
                required: false,
            },
            {
                name: "ownership",
                label: "Ownership",
                type: "select",
                placeholder: "Select Ownership",
                options: [
                    { value: "freehold", label: "Free Hold" },
                    { value: "nonehold", label: "Nones Hold" },
                    { value: "leasehold", label: "Lease Hold" },
                ],
                required: false,
            },
        ],
    },
    {
        title: "Property Permit",
        className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4",
        fields: [
            {
                name: "reraPermitNumber",
                label: "RERA Permit Number",
                type: "text",
                placeholder: "Enter RERA Permit Number",
                required: true,
            },
            {
                name: "reraPermitIssueDate",
                label: "RERA Permit Issue Date",
                type: "date",
                format: "dd-mm-yyyy",
                placeholder: "Enter RERA Permit Issue Date",
                required: false,
            },
            {
                name: "reraPermitExpirationDate",
                label: "RERA Permit Expiration Date",
                type: "date",
                format: "dd-mm-yyyy",
                placeholder: "Enter RERA Permit Expiration Date",
                required: false,
            },
            {
                name: "dtcmPermitNumber",
                label: "DTCM Permit Number",
                type: "text",
                placeholder: "Enter DTCM Permit Number",
                required: false,
            },
        ],
    },
    {
        title: "Pricing",
        className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4",
        fields: [
            {
                name: "price",
                label: "Price",
                type: "number",
                placeholder: "Enter Price",
                required: true,
            },
            {
                name: "rentalPeriod",
                label: "Rental Period (if rental)",
                type: "select",
                placeholder: "Select Rental Period",
                options: [
                    { value: "daily", label: "Daily" },
                    { value: "weekly", label: "Weekly" },
                    { value: "monthly", label: "Monthly" },
                    { value: "yearly", label: "Yearly" },
                ],
                required: false,
            },
            {
                name: "hidePrice",
                label: "Hide Price? (Property Finder only)",
                type: "select",
                placeholder: "Select yes/no?",
                options: [
                    { value: "yes", label: "yes" },
                    { value: "no", label: "no" },
                ],
                required: false,
            },
            {
                name: "paymentMethod",
                label: "Payment Method",
                type: "text",
                placeholder: "Enter Payment Method",
                required: false,
            },
            {
                name: "downPayment",
                label: "Down Payment",
                type: "number",
                placeholder: "Enter Down Payment",
                required: false,
            },
            {
                name: "noOfCheques",
                label: "No. of Cheques",
                type: "number",
                placeholder: "Enter No. of Cheques",
                required: false,
            },
            {
                name: "serviceCharge",
                label: "Service Charge",
                type: "number",
                placeholder: "Enter Service Charge",
                required: false,
            },
            {
                name: "financialStatus",
                label: "Financial Status",
                type: "select",
                placeholder: "Select Financial Status",
                options: [
                    { value: "mortgaged", label: "Mortgaged" },
                    { value: "cash", label: "Cash" },
                ],
                required: false,
            },
        ],
    },
];

export default formSections;
