export const dummyProperties = {
    data: [
        {
            id: 1,
            reference_number: "REF12345",
            title_deed: "TD12345",
            title_en: "Beautiful Villa",
            title_ar: "فيلا جميلة",
            description_en:
                "A beautiful villa located in the heart of the city.",
            description_ar: "فيلا جميلة تقع في قلب المدينة.",
            offering_type: "residential",
            property_type: "villa",
            size: "3500",
            unit_no: "10A",
            bedrooms: "4",
            bathrooms: "3",
            parkings: "2",
            furnished: "no",
            plot_size: "5000",
            lot_size: "3500",
            builtup_area: "3000",
            layout_type: "villa",
            ownership: "freehold",
            developer: {
                name: "Developer A",
                email: "developer@example.com",
                phone: "+1234567890",
            },
            agent: {
                name: "Agent B",
                email: "agent@example.com",
                phone: "+1234567890",
            },
            owner: {
                name: "Owner C",
                email: "owner@example.com",
                phone: "+1234567890",
            },
            build_year: 2015,
            landlord_name: "John Doe",
            landlord_email: "john@example.com",
            landlord_phone: "+1234567890",
            availability: "available",
            available_from: new Date(),
            rera_permit: "RP123456",
            rera_issue_date: new Date(),
            rera_expiry_date: new Date(),
            dtcm_permit: "DP123456",
            price: "500000",
            rental_period: "monthly",
            payment_method: "bank transfer",
            down_payment: 50000,
            cheques: 4,
            service_charge: 2000,
            financial_status: "mortgaged",
            price_in_gbp: "450000",
            amenities: ["swimming pool", "gym"],
            photo_urls: [
                "https://via.placeholder.com/600x400",
                "https://via.placeholder.com/600x400",
            ],
            tour_url: "https://example.com/tour",
            three_sixty_url: "https://example.com/360",
            qr_url: "https://example.com/qr",
            latitude: "25.276987",
            longitude: "55.296249",
            pf_location: "PF Location A",
            bayut_location: "Bayut Location B",
            floorplan_url: "https://example.com/floorplan",
            notes: "This is a note.",
            document_urls: [
                "https://example.com/doc1.pdf",
                "https://example.com/doc2.pdf",
            ],
            contract_expiry: new Date(),
            status: "live",
            hide_price: "no",
            pf_publish: true,
            bayut_publish: true,
            dubizzle_publish: true,
            website_publish: true,
            created_at: "2023-01-01",
            updated_at: "2023-01-02",
        },
        {
            id: 2,
            reference_number: "REF12346",
            title_deed: "TD12346",
            title_en: "Beautiful Villa",
            title_ar: "فيلا جميلة",
            description_en:
                "A beautiful villa located in the heart of the city.",
            description_ar: "فيلا جميلة تقع في قلب المدينة.",
            offering_type: "residential",
            property_type: "villa",
            size: "3500",
            unit_no: "10B",
            bedrooms: "4",
            bathrooms: "3",
            parkings: "2",
            furnished: "no",
            plot_size: "5000",
            lot_size: "3500",
            builtup_area: "3000",
            layout_type: "villa",
            ownership: "freehold",
            developer: {
                name: "Developer A",
                email: "developer@example.com",
                phone: "+1234567890",
            },
            agent: {
                name: "Agent B",
                email: "agent@example.com",
                phone: "+1234567890",
            },
            owner: {
                name: "Owner C",
                email: "owner@example.com",
                phone: "+1234567890",
            },
            build_year: 2015,
            landlord_name: "John Doe",
            landlord_email: "john@example.com",
            landlord_phone: "+1234567890",
            availability: "available",
            available_from: new Date(),
            rera_permit: "RP123456",
            rera_issue_date: new Date(),
            rera_expiry_date: new Date(),
            dtcm_permit: "DP123456",
            price: "500000",
            rental_period: "monthly",
            payment_method: "bank transfer",
            down_payment: 50000,
            cheques: 4,
            service_charge: 2000,
            financial_status: "mortgaged",
            price_in_gbp: "450000",
            amenities: ["swimming pool", "gym"],
            photo_urls: [
                "https://via.placeholder.com/600x400",
                "https://via.placeholder.com/600x400",
            ],
            tour_url: "https://example.com/tour",
            three_sixty_url: "https://example.com/360",
            qr_url: "https://example.com/qr",
            latitude: "25.276987",
            longitude: "55.296249",
            pf_location: "PF Location A",
            bayut_location: "Bayut Location B",
            floorplan_url: "https://example.com/floorplan",
            notes: "This is a note.",
            document_urls: [
                "https://example.com/doc1.pdf",
                "https://example.com/doc2.pdf",
            ],
            contract_expiry: new Date(),
            status: "live",
            hide_price: "no",
            pf_publish: true,
            bayut_publish: true,
            dubizzle_publish: true,
            website_publish: true,
            created_at: "2023-01-01",
            updated_at: "2023-01-02",
        },
        {
            id: 3,
            reference_number: "REF12347",
            title_deed: "TD12347",
            title_en: "Beautiful Villa",
            title_ar: "فيلا جميلة",
            description_en:
                "A beautiful villa located in the heart of the city.",
            description_ar: "فيلا جميلة تقع في قلب المدينة.",
            offering_type: "residential",
            property_type: "villa",
            size: "3500",
            unit_no: "10C",
            bedrooms: "4",
            bathrooms: "3",
            parkings: "2",
            furnished: "no",
            plot_size: "5000",
            lot_size: "3500",
            builtup_area: "3000",
            layout_type: "villa",
            ownership: "freehold",
            developer: {
                name: "Developer A",
                email: "developer@example.com",
                phone: "+1234567890",
            },
            agent: {
                name: "Agent B",
                email: "agent@example.com",
                phone: "+1234567890",
            },
            owner: {
                name: "Owner C",
                email: "owner@example.com",
                phone: "+1234567890",
            },
            build_year: 2015,
            landlord_name: "John Doe",
            landlord_email: "john@example.com",
            landlord_phone: "+1234567890",
            availability: "available",
            available_from: new Date(),
            rera_permit: "RP123456",
            rera_issue_date: new Date(),
            rera_expiry_date: new Date(),
            dtcm_permit: "DP123456",
            price: "500000",
            rental_period: "monthly",
            payment_method: "bank transfer",
            down_payment: 50000,
            cheques: 4,
            service_charge: 2000,
            financial_status: "mortgaged",
            price_in_gbp: "450000",
            amenities: ["swimming pool", "gym"],
            photo_urls: [
                "https://via.placeholder.com/600x400",
                "https://via.placeholder.com/600x400",
            ],
            tour_url: "https://example.com/tour",
            three_sixty_url: "https://example.com/360",
            qr_url: "https://example.com/qr",
            latitude: "25.276987",
            longitude: "55.296249",
            pf_location: "PF Location A",
            bayut_location: "Bayut Location B",
            floorplan_url: "https://example.com/floorplan",
            notes: "This is a note.",
            document_urls: [
                "https://example.com/doc1.pdf",
                "https://example.com/doc2.pdf",
            ],
            contract_expiry: new Date(),
            status: "live",
            hide_price: "no",
            pf_publish: true,
            bayut_publish: true,
            dubizzle_publish: true,
            website_publish: true,
            created_at: "2023-01-01",
            updated_at: "2023-01-02",
        },
    ],
};